---
- name: Look at all profiles and return matches using grep
  hosts: hwt-pimpl01
  
  vars:
    prof_val: protectedwebmethods
  
  become: true
  gather_facts: false
  tasks:
  - name: check all profiles
    shell: "grep -r {{prof_val}} /sapmnt/{{ sid }}/profile/*"
    register: out
    ignore_errors: true

  - debug: var=out.stdout_lines
